# Generated by Django 5.2.8 on 2025-11-20 20:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('street', models.CharField()),
                ('zipcode', models.IntegerField(validators=[django.core.validators.MinValueValidator(501), django.core.validators.MaxValueValidator(99950)])),
                ('state', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('account_type', models.CharField(default='Regular')),
                ('email', models.EmailField(max_length=254)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
                ('middle_name', models.CharField(null=True)),
                ('age', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(unique=True)),
                ('number_of_employees', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('owner', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField()),
                ('in_stock', models.PositiveIntegerField()),
                ('rating', models.CharField(null=True)),
            ],
        ),
    ]
